### ISSUE TITLE
Support more OS?

### ISSUE THREAD

**Issue by HouLinwei** [cesarghali/OS-Fingerprinting#1]
hi,
    I want to know the OS fingerprints  of iOS and Android(maybe all Android devices are Linux 2.6 ?). Can this project plan to support this? And I notice your project use TCP option fields' implementation of different operating systems. Is there any documents about this(I want to know more about the detail of TCP's implementation)?
    Thank you.

**Comment by cesarghali** [comment]
Hi HouLinwei,

I'm not maintaining this project anymore. That being said, there's no plan to support more OSes. If you have time to do so, please feel free to send a PR.

Cheers!
Cesar
