### ISSUE TITLE
Seems to not work, always gives all OS as Possible OS

### ISSUE THREAD

**Issue by ohmtrivedi** [cesarghali/OS-Fingerprinting#2]
I have been trying to run the Attack tool on various remote IPs (do not belong to me and outside of my network) which I have as part of my research. But I am always getting default answer for all such IPs. Using nmap, I verified that port 80 is open on the corresponding IP as well the OS on target is one of the OS from the list of OS which the tool checks for. Yet, I am not getting the answer. Is there anything I am doing wrong here? Kindly find below output of nmap as well of ./osfp_tool.  Note: I also made a modification for checking if the tool is able to send a http_request to the target ("Sent 16 bytes to 14.141.146.139 on 80."). So, that shows connection is also successful.

root@kali:~/Documents/msThesis/OS-Fingerprinting-Cesarghali/Attack# nmap -O 14.141.146.139
Starting Nmap 7.70 ( https://nmap.org ) at 2018-09-02 07:45 EDT
Nmap scan report for 14.141.146.139.static-Mumbai.vsnl.net.in (14.141.146.139)
Host is up (0.25s latency).
Not shown: 982 closed ports
PORT     STATE    SERVICE
22/tcp   open     ssh
25/tcp   filtered smtp
53/tcp   open     domain
80/tcp   open     http
2323/tcp open     3d-nfsd
3128/tcp open     squid-http
4000/tcp open     remoteanything
4343/tcp open     unicall
4662/tcp filtered edonkey
5000/tcp filtered upnp
6346/tcp filtered gnutella
6839/tcp filtered unknown
6881/tcp filtered bittorrent-tracker
7001/tcp filtered afs3-callback
7002/tcp filtered afs3-prserver
8000/tcp filtered http-alt
9002/tcp filtered dynamid
9080/tcp filtered glrpc
Aggressive OS guesses: Linux 2.6.32 (96%), IPFire 2.11 firewall (Linux 2.6.32) (94%), Linux 2.6.31 - 2.6.32 (93%), Linux 2.6.15 - 2.6.26 (likely embedded) (92%), Linux 2.6.32 - 2.6.33 (92%), Linux 2.6.32 - 2.6.35 (92%), Linux 2.6.24 (Debian) (92%), Linux 2.6.32 - 2.6.39 (92%), Linux 2.6.30 (91%), IGEL UD3 thin client (Linux 2.6) (91%)
No exact OS matches for host (test conditions non-ideal).
Network Distance: 20 hops

OS detection performed. Please report any incorrect results at https://nmap.org/submit/ .
Nmap done: 1 IP address (1 host up) scanned in 16.22 seconds
root@kali:~/Documents/msThesis/OS-Fingerprinting-Cesarghali/Attack# sudo ./osfp_tool 14.141.146.139

Initializing the packet sniffer...
Sniffing Device: eth0
OS fingerprinting the network device [14.141.146.139] through port [80]...
Sent 16 bytes to 14.141.146.139 on 80.

-> Operating Systems probability weight:
   -------------------------------------
---> Linux 2.1                      0.0
---> Linux 2.0                      0.0
---> Linux 2.0.3x                   0.0
---> Linux 2.2                      0.0
---> Linux 2.4                      0.0
---> Linux 2.6                      0.0
---> Windows 3.11                   0.0
---> Windows 95                     0.0
---> Windows 95b                    0.0
---> Windows 98                     0.0
---> Windows ME no SP               0.0
---> Windows NT 4.0 SP6a            0.0
---> Windows 2000 SP2+              0.0
---> Windows 2000 SP3               0.0
---> Windows 2000 SP4               0.0
---> Windows XP SP1+                0.0
---> Windows 2K3                    0.0
---> Windows Vista (beta)           0.0
---> MacOS 7.3-8.6 (OTTCP)          0.0
---> MacOS 8.1-8.6 (OTTCP)          0.0
---> MacOS 8.6                      0.0
---> MacOS 9.0-9.2                  0.0
---> MacOS 9.1 (OT 2.7.4)           0.0
---> MacOS 10.2.6                   0.0

-> Possible Operating Systems:
--------------------------------
---> Linux 2.1
---> Linux 2.0
---> Linux 2.0.3x
---> Linux 2.2
---> Linux 2.4
---> Linux 2.6
---> Windows 3.11
---> Windows 95
---> Windows 95b
---> Windows 98
---> Windows ME no SP
---> Windows NT 4.0 SP6a
---> Windows 2000 SP2+
---> Windows 2000 SP3
---> Windows 2000 SP4
---> Windows XP SP1+
---> Windows 2K3
---> Windows Vista (beta)
---> MacOS 7.3-8.6 (OTTCP)
---> MacOS 8.1-8.6 (OTTCP)
---> MacOS 8.6
---> MacOS 9.0-9.2
---> MacOS 9.1 (OT 2.7.4)
---> MacOS 10.2.6

**Comment by cesarghali** [comment]
Hi ohmtrivedi,

I'm not maintaining this project anymore and I don't think I'll have time to do so. If you managed to find a solution to this issue, please feel free to send a PR.

Cheers!
Cesar

**Comment by ohmtrivedi** [comment]
Hi @cesarghali ,
Thanks for your response. No, I have not been able to figure out the issue, not that experienced on this topic yet. But yes, if somehow I do find out, I will definitely let you know.
Meanwhile, can you point me to the references/resources you used for the stateless attacks in your detection tool? I am not able to find any such material to learn why such packets lead to OSF.
